using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class ScreenCalculator : MonoBehaviour
{
    public static ScreenCalculator instance;
    private float height;
    private float width;

    public float Height
    {
        get
        {
            return height;
        }
    }

    public float Width
    {
        get
        {
            return width;
        }
    }
    void Awake()
    {
        if (instance == null)
        {
            instance = this;
        }
        else if(instance != null)
        {
            Destroy(gameObject);
            
        }

        height = Camera.main.orthographicSize;
        width = height * Camera.main.aspect;

    }

   
    // Update is called once per frame
    void Update()
    {
       
    }

    

    


    
}
